version: '3.8'

services:

  gateway:
    build: ./gateway
    ports:
      - "5000:5000"
    env_file:
      - ./gateway/.env
    depends_on:
      - auth_service
      - user_service
      - product_service
      - cart_service
      - order_service

  auth_service:
    build: ./services/auth_service
    ports:
      - "5001:5001"
    env_file:
      - ./services/auth_service/.env

  user_service:
    build: ./services/user_service
    ports:
      - "5002:5002"
    env_file:
      - ./services/user_service/.env

  product_service:
    build: ./services/product_service
    ports:
      - "5003:5003"
    env_file:
      - ./services/product_service/.env

  cart_service:
    build: ./services/cart_service
    ports:
      - "5004:5004"
    env_file:
      - ./services/cart_service/.env

  order_service:
    build: ./services/order_service
    ports:
      - "5005:5005"
    env_file:
      - ./services/order_service/.env